# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c75c0e42862cc20d19f22c52a5851beb7d2aab1eb87f7eb1e87aaba1c20b22acf0ee3d8baf8f416d56071c40ec0db6822e1c54593230edf0e477aff782ce15

test:
  secret_key_base: 952528bf229e6e878811dbd0d78595ae7d16066956eb1694e3c863e25704944500880849c812dcc33a1a8a68579167e3a30629bbb275ab05e6fbaabac02ff12c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
